# Custom Language File for Launcher Customizer

[ejs.app]
title = "Site 999 Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Site-999/Site-999Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.site-999.com"

[ejs.settings]
sourceGithubLink = "https://github.com/Site-999/Site-999Launcher"
supportLink = "https://github.com/Site-999/Site-999Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Site 999"
welcomeDescription = ""
welcomeDescCTA = ""
